name: store_getx_app
description: "Store GetX App Template"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/payment/
    - assets/icons/categories/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
